### ISSUE TITLE
lsmeans when factors interact with continuous variable

### ISSUE THREAD

**Issue by xmesmin** [rvlenth/lsmeans#5]
Hello,

First thank you for this very useful package.
I am computing predicted marginal means with 'lsmeans', on a model where qualitative factors interact significantly with a continuous variable. When the interaction is between the focus factor and another factor, the function displays : "Results are averaged over the levels of: ...". But when there is an interaction with a continuous variable, what value is taken by default to predict mean values? Is it 0, the mean of the continuous variable in the dataset used, or something else? It is of importance as the order of the modalities of the qualitative factor may change with the variations in the quantitative variable.
Maybe it has no sense to compute single lsmeans in these situations, as the only way to have a good idea of the effects of the variables would be to plot predicted values for each modality of the qualitative factor against the continuous variable (or at least against several values)...

Sincerely,

**Comment by rvlenth** [comment]
Yes -- by default, covariates are reduced to their means, but you can change that using the `at` or `cov.reduce` arguments. See `help("lsmeans=package")`, `help("ref.grid")`, and `vignette("using-lsmeans")`. The latter has a discussion of reference grids and how they are used to obtain least-squares means (or PMMs). If there are shortcomings in the documentation that you feel don't make this clear, let me know.

Since you have a covariate interacting with a factor, you may also be interested in the `lstrends()` function, which can compare the slopes of the fitted lines at the different factor levels. See `help("lstrends")`; there is also an example in the vignette.

**Comment by xmesmin** [comment]
Thank you for this quick answer!
