### ISSUE TITLE
Bug in lsmeans with gls objects

### ISSUE THREAD

**Issue by cbolen1** [rvlenth/lsmeans#8]
Hi,
First off, thanks for the excellent package. We're actually using it as a dependency for our package on bioconductor, and it has been excellent so far. However, a bug cropped up in the latest version of R/lsmeans that seems to be causing problems. 

Our workflow first fits a generalized least squares model using the gls function in the nlme package. We then feed that into lsmeans. This works great for most models (and worked for all models until a couple months ago), but it's now failing whenever the gls model contains two factors that interact with each other. 

Below is a pet example that recreates this bug:
```
dat = data.frame(
    Treatment = rep(c("C","T"),25), 
    Gender = rep(sample(c("M","F"),25,T),each = 2), 
    Age  = rep(sample(25:75, 25,T), each=2),
    y=rnorm(50)
)

##works fine
g = gls(y ~ Treatment*Age, data=dat)
lsmeans(g, ~Treatment)

##does not work
g = gls(y ~ Treatment*Gender, data=dat)
lsmeans(g, ~Treatment)
```

The bug I get back is the following:
```
Error in seq_len(ncol(fac)) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(ncol(fac)) : first element used of 'length.out' argument
```

and after some digging, it appears to be triggered in the `.find_nests` function that's called in `ref_grid`. Apparently the function is expecting the "terms" object to have an attribute "factors", which it does not have. 

I'm not sure when this bug cropped up; it might be due to changes in the nlme package. However, I'm hoping that this is something that's easy to fix. Let me know if you need any more details.

Best,
Chris

**Comment by rvlenth** [comment]
Thanks for the report. And thanks for tracking it down. I will take a look. If it's indeed in `.find.nests()`, that bug is new as of the latest CRAN version of **lsmeans**. I had thought that `factors` is a *required* component of a `terms` object. I'll check into that too, but in any case I'll try to get **lsmeans** to work. And I'll check `lme` objects too...

Sent from my iPhone

On Sep 11, 2017, at 9:41 AM, cbolen1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
First off, thanks for the excellent package. We're actually using it as a dependency for our package on bioconductor, and it has been excellent so far. However, a bug cropped up in the latest version of R/lsmeans that seems to be causing problems.

Our workflow first fits a generalized least squares model using the gls function in the nlme package. We then feed that into lsmeans. This works great for most models (and worked for all models until a couple months ago), but it's now failing whenever the gls model contains two factors that interact with each other.

Below is a pet example that recreates this bug:

dat = data.frame(
    Treatment = rep(c("C","T"),25),
    Gender = rep(sample(c("M","F"),25,T),each = 2),
    Age  = rep(sample(25:75, 25,T), each=2),
    y=rnorm(50)
)

##works fine
g = gls(y ~ Treatment*Age, data=dat)
lsmeans(g, ~Treatment)

##does not work
g = gls(y ~ Treatment*Gender, data=dat)
lsmeans(g, ~Treatment)


The bug I get back is the following:

Error in seq_len(ncol(fac)) :
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(ncol(fac)) : first element used of 'length.out' argument


and after some digging, it appears to be triggered in the .find_nests function that's called in ref_grid. Apparently the function is expecting the "terms" object to have an attribute "factors", which it does not have.

I'm not sure when this bug cropped up; it might be due to changes in the nlme package. However, I'm hoping that this is something that's easy to fix. Let me know if you need any more details.

Best,
Chris

**Comment by rvlenth** [comment]
Chris,

Earlier I said: Not questioning your finding, but I can’t reproduce the error:
```
... (example deleted)
```
I couldn't reproduce it because I had already fixed it. (The `gls` support uses `getCovariateFormula()` instead of `terms()`, which strips off any conditioning portions of the formula. But this is in fact of class `formula`, not `terms`. In the next CRAN update, I'll incorporate a true `terms` object there so it can find the nesting structure, if present. In the meantime, the `nesting` argument of `ref.grid()` is available.

**Comment by rvlenth** [comment]
Ah - I forgot that I had already fixed this bug -- see Aug 31 update on github! If you re-install from the github site, you should be OK.

**Comment by cbolen1** [comment]
Confirmed! The Github version works for me as well.

Out of curiosity, what's the schedule for this update being pushed to CRAN?

**Comment by rvlenth** [comment]
At least a month, I'd say. I am making huge changes to its internals, and I want to check everything pretty thoroughly. Also need to completely rewrite the vignettes, or at least provide a good excuse for not doing so yet. If you're curious, look at the "rvlhacks" branch, which I will try to keep in shape to at least load, but not necessarily to pass checks.

**Comment by cbolen1** [comment]
Thanks Russel,

I'll put in a temporary fix on my end, and I'll keep an eye out for the new version being posted to CRAN.
